### ISSUE TITLE
integrate spans makes the app to crash

### ISSUE THREAD

**Issue by danielo515** [standard-ai/tracing-gstreamer#15] opened 2023-07-05 15:33 UTC
Hello.
We are very interested into integrating gstreamer logs into our telemetry, so this crate looks super useful. However, when I try to setup the basic example, as soon as I call the integrate_spans function it crashes the app. 
So given this setting up:

```rs
        tracing_gstreamer::integrate_events();
        gst::debug_remove_default_log_function();
        gst::debug_set_default_threshold(gst::DebugLevel::Memdump);
        gst::init().context("Failed to initialize GStreamer")?;
        tracing_gstreamer::integrate_spans(); // this makes the app panic
        ges::init()
            .context("Failed to initialize GStreamer Editing Services")?;

        let timeline = ges::Timeline::new();

        let pipeline = ges::Pipeline::new();
```

And this gst dependencies:

```toml
gst = { package = "gstreamer", git = "https://gitlab.freedesktop.org/thiblahute/gstreamer-rs.git", branch = "meta_tags", features = [
  "v1_18",
] }

ges = { package = "gstreamer-editing-services", git = "https://gitlab.freedesktop.org/thiblahute/gstreamer-rs.git", branch = "meta_tags", features = [
  "v1_24",
] }
gst_pbutils = { package = "gstreamer-pbutils", git = "https://gitlab.freedesktop.org/thiblahute/gstreamer-rs.git", branch = "meta_tags", features = [
  "v1_20",
] }
gst_video = { package = "gstreamer-video", git = "https://gitlab.freedesktop.org/thiblahute/gstreamer-rs.git", branch = "meta_tags" }
gst_controller = { package = "gstreamer-controller", git = "https://gitlab.freedesktop.org/thiblahute/gstreamer-rs.git", branch = "meta_tags" }

```

I get this panic:
```
ile:///tmp/out.mp4"}: gstreamer::GST_ELEMENT_PADS: no such pad 'sink' in element "(null)"
thread 'main' panicked at 'assertion failed: !ptr.is_null()', /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.10/src/gstring.rs:1900:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:117:5
   3: <glib::gstring::GString as glib::translate::FromGlibPtrFull<*mut u8>>::from_glib_full
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.10/src/gstring.rs:1900:9
   4: glib::translate::from_glib_full
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.10/src/translate.rs:1631:5
   5: <glib::gstring::GString as glib::translate::FromGlibPtrFull<*mut i8>>::from_glib_full
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.10/src/gstring.rs:1916:9
   6: glib::translate::from_glib_full
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.17.10/src/translate.rs:1631:5
   7: <O as gstreamer::auto::object::GstObjectExt>::name
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gstreamer-0.20.7/src/auto/object.rs:188:18
   8: tracing_gstreamer::tracer::TracingTracerPriv::pad_pre::{{closure}}
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-gstreamer-0.5.0/src/tracer.rs:69:62
   9: core::option::Option<T>::map
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:1099:29
  10: tracing_gstreamer::tracer::TracingTracerPriv::pad_pre
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-gstreamer-0.5.0/src/tracer.rs:69:40
  11: <tracing_gstreamer::tracer::TracingTracerPriv as gstreamer::subclass::tracer::TracerImpl>::pad_query_pre
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-gstreamer-0.5.0/src/tracer.rs:133:9
  12: <T as gstreamer::subclass::tracer::TracerImplExt>::register_hook::callback
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gstreamer-0.20.7/src/subclass/tracer.rs:315:9
  13: gst_pad_query
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gstreamer/gst/gstpad.c:4185:3
  14: bin_query_generic_fold
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gstreamer/gst/gstbin.c:4208:11
  15: gst_iterator_fold
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gstreamer/gst/gstiterator.c:618:14
  16: bin_iterate_fold
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gstreamer/gst/gstbin.c:4237:12
  17: gst_bin_query
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gstreamer/gst/gstbin.c:4321:9
  18: gst_element_query
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gstreamer/gst/gstelement.c:2100:11
  19: gst_element_decorate_stream_id_internal
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gstreamer/gst/gstutils.c:4009:9
  20: nle_composition_init
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gst-editing-services/plugins/nle/nlecomposition.c:1198:14
  21: _g_type_create_instance
  22: _g_object_new_internal
  23: _g_object_new_with_properties
  24: gst_element_factory_create_with_properties
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gstreamer/gst/gstelementfactory.c:494:28
  25: gst_element_factory_make_with_properties
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gstreamer/gst/gstelementfactory.c:700:13
  26: ges_track_init
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gst-editing-services/ges/ges-track.c:944:29
  27: _g_type_create_instance
  28: _g_object_new_internal
  29: _g_object_new_valist
  30: _g_object_new
  31: ges_video_track_new
             at /Users/danielo/projects/gstreamer/builddir/../subprojects/gst-editing-services/ges/ges-video-track.c:178:9
  32: gstreamer_editing_services::auto::video_track::VideoTrack::new
             at /Users/danielo/.cargo/git/checkouts/gstreamer-rs-7a0fd8b7d0e8b114/cda3131/gstreamer-editing-services/src/auto/video_track.rs:24:33
  33: video_renderer::Renderer::configure_caps
             at ./video_renderer/src/lib.rs:83:27
  34: video_renderer::Renderer::render
             at ./video_renderer/src/lib.rs:472:9
  35: cli::main::{{closure}}
             at ./cli/src/main.rs:93:5
  36: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:63
  37: tokio::runtime::coop::with_budget
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  38: tokio::runtime::coop::budget
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  39: tokio::runtime::park::CachedParkThread::block_on
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/park.rs:283:31
  40: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/context.rs:315:13
  41: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:66:9
  42: tokio::runtime::runtime::Runtime::block_on
             at /Users/danielo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/runtime.rs:304:45
  43: cli::main
             at ./cli/src/main.rs:105:5
  44: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5

```

**Comment by nagisa** [comment] 2023-07-05 21:28
Hm, it would be great to have a full minimal reproducer, rather than just a snippet of the code. That said, this looks like it could be an issue with the upstream gstreamer or the gstreamer-rs bindings (and is exposed by `tracing-gstreamer`.) If logs are to be believed, it looks like `gst_pad_query` is being called on a pad that has a `nullptr` element as its parent?

I’m not entirely sure if that's valid gstreamer semantic or not, but if this assertion gets fired, then there's an abstraction leak somewhere in either of these upstream projects.

**Comment by nagisa** [comment] 2023-07-05 21:29
cc @sdroege may have more insight? But I don't expect them to give this much time without a MCVE.

**Comment by sdroege** [comment] 2023-07-06 09:53
I think this is related to https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4975 (CC @thiblahute)

**Comment by thiblahute** [comment] 2023-07-06 18:36
This one should be fixed in GStreamer main now that https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4975 is merged.

**Comment by nagisa** [comment] 2023-07-06 18:46
Closing. Please let me know if this is still happens to be reproducible.

NB: You will need to use git dependencies to verify the fix.

**Closed as completed by nagisa** 2023-07-06 18:46 UTC
